### ISSUE TITLE
Can't set mask interaction nor color in tilemap componentes

### ISSUE THREAD

**Issue by Nrosa01** [skner-dev/DualGrid#2]
Since both Tilemap and TilemapRenderer are managed by DualGridTilemapModule, you can't change tilemap color or tilemaprenderer mask interaction with the inpsector, although code can set that but it would be nice to unlock those properties in the inspector

**Comment by skner-dev** [comment]
The reason these are currently blocked for edit in the inspector, was that I wasn't aware of all the consequences that the options in  both components could have in the DualGridTilemapModule script. So, in order to deliver this package faster, I decided to block them for now and I'd investigate later. Essentially, it's not supported yet, as I haven't studied any settings different from the default ones.

However, if you want, you can comment or delete the editor scripts which do this:
- Editor/Editors/Restricted###Editor.cs

For the time being, I'll be investigating if the DualGridTilemapModule breaks with any of the settings, and if not, I'll unlock it.

**Comment by Nrosa01** [comment]
I know I can delete that, I already did some test and the only thing that must be locked is the transform component of both tilemaps. Then, in the data tilemap component, everything must be locked. In the render tilemap component, Color should be unlocked. Now in the render tilemaprendererer component, everything can be unlocked. I'm a little busy testing stuff right now but next year I'll find some time to make a PR to help with this.

**Comment by Nrosa01** [comment]
I did a PR #4 for this. I'm currently using a local copy of the repo because this silly thing really annoyed me. I also fixed the transform component render. Cheers! ^^
